<h1>Logistic Regression</h1>

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('daibetes.xlsx')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [7]:
X = df.drop('Outcome', axis = 1)
y= df['Outcome'].values
print(df.shape, X.shape, y.shape)

(768, 9) (768, 8) (768,)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size =0.2 , random_state = 32)

In [28]:
model = LogisticRegression(max_iter=1000)

In [29]:
model.fit(X_train ,y_train)

LogisticRegression(max_iter=1000)

In [30]:
y_pred = model.predict(X_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0])

In [31]:
matrix = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
print(matrix)
print(acc)
print(report)

[[85 14]
 [19 36]]
0.7857142857142857
              precision    recall  f1-score   support

           0       0.82      0.86      0.84        99
           1       0.72      0.65      0.69        55

    accuracy                           0.79       154
   macro avg       0.77      0.76      0.76       154
weighted avg       0.78      0.79      0.78       154

In [32]:
matrix

array([[85, 14],
       [19, 36]])

In [33]:
acc

0.7857142857142857

In [34]:
print(report)

              precision    recall  f1-score   support

           0       0.82      0.86      0.84        99
           1       0.72      0.65      0.69        55

    accuracy                           0.79       154
   macro avg       0.77      0.76      0.76       154
weighted avg       0.78      0.79      0.78       154

## Building linear regression on diabetes data

In [35]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(X_train, y_train)

LinearRegression()

In [36]:
y_pred_linreg = linreg.predict(X_test)
y_pred_linreg

array([ 4.97524626e-01,  2.94524383e-01,  4.55137485e-01,  1.27919839e-01,
        4.17955415e-01,  6.74009015e-02,  4.28862582e-01,  6.17693158e-01,
        7.51522398e-01,  2.68257159e-02,  3.03832966e-01,  3.27247929e-02,
        8.42556526e-02, -2.04749362e-01,  8.85083952e-02,  1.18965073e-01,
        4.57467081e-01,  7.17256648e-02,  5.54865952e-01,  3.56345449e-01,
        3.49745594e-01,  4.05730366e-01,  2.94497165e-01,  5.63863344e-01,
        2.98346788e-01,  1.24201070e-01,  8.35507479e-01,  6.43794435e-02,
        1.01827747e-01,  1.59511632e-01,  5.37425665e-01,  5.42820030e-01,
        3.24766561e-01,  3.80228208e-01,  5.21640436e-01,  2.70200939e-01,
        7.12794817e-01, -1.67988050e-01,  2.62807344e-01,  6.98918773e-01,
        7.51231563e-01,  5.58383853e-01,  5.93229615e-01,  4.25424467e-01,
        2.31509691e-01,  2.19453661e-01,  9.82605313e-01,  4.29780420e-01,
        6.59642400e-01,  3.91555946e-01,  4.75274519e-01,  5.27420453e-01,
        1.06463160e-01, -1.50805775e-01,  4.38487292e-01,  6.45455993e-01,
        5.06581103e-01,  1.94111574e-01,  8.60573981e-03,  3.11900553e-01,
        1.72468390e-01,  4.12644366e-01, -7.63950079e-04,  1.96735150e-01,
        6.67204043e-01, -2.85705249e-02,  1.39763617e-01,  2.24966980e-01,
        2.57634695e-01,  2.24625511e-01,  2.81374942e-01,  2.43023736e-01,
        8.41839152e-01,  5.65108781e-01,  2.25023373e-01,  4.58976774e-01,
        7.35754778e-01,  3.26816897e-01,  2.97990264e-01,  4.64374131e-01,
       -9.68741974e-03,  1.14213816e-01,  3.77718149e-01,  2.94185056e-01,
        3.93385557e-01,  5.99090253e-01,  2.55675239e-01,  1.12621128e-01,
        1.63934387e-02,  6.87257207e-01,  3.99458173e-01,  9.95782758e-01,
        5.26094209e-01,  9.39402301e-02,  2.87319248e-01,  2.88917979e-01,
        8.67851926e-01,  5.64772683e-01,  8.24409081e-01,  7.21909570e-01,
        5.65215362e-01, -6.66357555e-02,  4.33375199e-01,  4.39796321e-01,
        6.01420430e-01,  1.73555589e-01,  1.35083896e-01,  1.35732583e-01,
        3.70573493e-02,  2.08236970e-01,  1.61752575e-01,  4.29237033e-01,
        3.66477557e-01,  2.92557548e-01,  3.18073105e-01,  6.88927375e-01,
        9.53622965e-01,  1.86684534e-01, -2.92425412e-01,  1.88534522e-01,
        3.52711354e-01,  3.62953884e-01,  1.13671960e-01,  5.95218475e-01,
        5.65705386e-01,  4.57791712e-02,  6.84366589e-01,  7.84615731e-01,
        2.11068456e-01, -4.22062975e-02,  1.02807716e+00,  2.39086831e-01,
       -1.53057249e-02,  6.06285428e-01,  5.88225534e-01,  7.45143562e-01,
        4.45527529e-01,  1.60238364e-01,  3.23941551e-01,  6.39722355e-01,
        7.37470567e-01,  1.21839608e-01,  6.52082590e-01,  3.04507356e-01,
        2.40383555e-01,  6.60567451e-01,  3.37254617e-01,  2.64151356e-03,
        7.14098099e-01,  6.01163580e-01,  1.51543453e-01,  1.57523181e-01,
        6.39590604e-01,  3.68280209e-01])

In [37]:
print(y_pred_linreg.max())
print(y_pred_linreg.min())

1.0280771634073664
-0.2924254119054527

In [38]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error,r2_score
print( mean_squared_error(y_test, y_pred_linreg))
print(mean_absolute_error(y_test, y_pred_linreg))
print( root_mean_squared_error(y_test, y_pred_linreg))
print( r2_score(y_test, y_pred_linreg))

0.1421771836910383
0.31778501025119804
0.3770638986843454
0.3807393777012553

In [39]:
pred_list = y_pred_linreg.tolist()
print(pred_list)

[0.49752462624638905, 0.2945243827765436, 0.45513748496477646, 0.12791983867355494, 0.41795541510469914, 0.0674009015401289, 0.42886258214379414, 0.6176931584332961, 0.7515223977493781, 0.026825715911598547, 0.3038329659666503, 0.03272479285210994, 0.08425565264399026, -0.20474936240429342, 0.08850839524397514, 0.118965073204227, 0.45746708087417765, 0.0717256647882909, 0.5548659520249994, 0.35634544920454414, 0.34974559408313355, 0.4057303662325984, 0.29449716450295416, 0.5638633443726928, 0.29834678830547, 0.12420107035442851, 0.8355074786495893, 0.0643794434815751, 0.10182774693298813, 0.159511632496665, 0.5374256653716885, 0.5428200296464543, 0.32476656132089055, 0.3802282081088777, 0.5216404355179409, 0.2702009393172464, 0.7127948168926317, -0.16798805015395035, 0.2628073442075971, 0.6989187733960032, 0.7512315633467515, 0.5583838529649381, 0.5932296149314269, 0.42542446749506024, 0.23150969102789465, 0.21945366077209982, 0.9826053129715908, 0.42978042049567633, 0.6596424000691881, 0.3915559458859541, 0.4752745185883487, 0.5274204532170164, 0.10646315961610209, -0.1508057748612821, 0.4384872922205454, 0.64545599261402, 0.5065811028259566, 0.19411157371577148, 0.008605739814575575, 0.31190055264331273, 0.17246839016503324, 0.41264436605423893, -0.0007639500787657294, 0.1967351502297643, 0.6672040433364874, -0.028570524851830204, 0.1397636172671224, 0.22496697952967515, 0.2576346950249473, 0.2246255108721804, 0.2813749422146319, 0.24302373571505886, 0.8418391518827992, 0.5651087805191808, 0.22502337345276668, 0.45897677365250056, 0.7357547776490045, 0.3268168969974943, 0.29799026396343264, 0.46437413059783617, -0.009687419739316416, 0.11421381639733597, 0.3777181486895784, 0.2941850564062831, 0.3933855570516427, 0.5990902531700837, 0.2556752391894841, 0.11262112844028671, 0.01639343874088872, 0.6872572068029661, 0.39945817349533597, 0.9957827577287663, 0.526094209148118, 0.0939402301417408, 0.2873192481181974, 0.28891797899061555, 0.8678519256757196, 0.5647726827139445, 0.8244090808752931, 0.7219095701057583, 0.565215362211763, -0.06663575550303258, 0.4333751992521051, 0.4397963205910531, 0.6014204295930077, 0.17355558940056137, 0.13508389610719518, 0.1357325830811006, 0.037057349346409474, 0.20823697043213274, 0.16175257461206227, 0.4292370332767901, 0.3664775566951828, 0.29255754791902544, 0.31807310492381613, 0.6889273746911064, 0.9536229651938697, 0.18668453442648092, -0.2924254119054527, 0.18853452166753248, 0.352711354358173, 0.36295388434789255, 0.11367196031756022, 0.5952184748241367, 0.5657053864516546, 0.04577917120852515, 0.6843665889645005, 0.7846157309314024, 0.21106845564838195, -0.04220629752154692, 1.0280771634073664, 0.2390868312908394, -0.015305724919688624, 0.6062854277579663, 0.5882255342741274, 0.7451435615244972, 0.44552752914358584, 0.1602383642138554, 0.3239415511345467, 0.6397223549799225, 0.7374705671371149, 0.12183960759928814, 0.6520825902529135, 0.30450735603385337, 0.24038355509500042, 0.6605674511109718, 0.3372546174360662, 0.0026415135567654513, 0.7140980987993459, 0.6011635800039259, 0.1515434531890124, 0.15752318116840658, 0.6395906041106298, 0.3682802092543678]

In [40]:
def sig(x):
    result= 1/(1 + np.exp(-x))
    return result

In [41]:
data_for_threshold = []
for i in pred_list:
    data_for_threshold.append(sig(i))

In [42]:
print(data_for_threshold)

[np.float64(0.6218774330855028), np.float64(0.5731034141722237), np.float64(0.6118600204418355), np.float64(0.5319364222764833), np.float64(0.6029938952895643), np.float64(0.516843849233489), np.float64(0.6056020308682198), np.float64(0.6496937118355284), np.float64(0.6795103314963664), np.float64(0.50670602683401), np.float64(0.5753792487707846), np.float64(0.5081804681792167), np.float64(0.5210514609144963), np.float64(0.44899073715330445), np.float64(0.5221126652967919), np.float64(0.5297062412970084), np.float64(0.6124131255848492), np.float64(0.5179237326962496), np.float64(0.6352637904732858), np.float64(0.5881554833849013), np.float64(0.586555884786051), np.float64(0.6000636602608508), np.float64(0.5730967550480021), np.float64(0.6373459715280128), np.float64(0.5740383258205272), np.float64(0.5310104141895164), np.float64(0.6975181963027057), np.float64(0.5160893041255813), np.float64(0.5254349628359682), np.float64(0.5397935683834449), np.float64(0.6312133589433546), np.float64(0.632468184311829), np.float64(0.5804854584137187), np.float64(0.5939281427757823), np.float64(0.6275312749251601), np.float64(0.5671422346096809), np.float64(0.6710184178121106), np.float64(0.458101472468276), np.float64(0.5653262735366169), np.float64(0.6679480067333442), np.float64(0.6794469914252108), np.float64(0.6360785126405009), np.float64(0.6441058257376518), np.float64(0.6047805458859952), np.float64(0.5576202973599864), np.float64(0.5546442857002386), np.float64(0.727624861396903), np.float64(0.6058212336548755), np.float64(0.6591800540130041), np.float64(0.5966572054120313), np.float64(0.6166314020013585), np.float64(0.6288812729487125), np.float64(0.5265906788551021), np.float64(0.46236984587828633), np.float64(0.607898523794243), np.float64(0.6559857516701452), np.float64(0.6240046638083434), np.float64(0.5483760906187963), np.float64(0.5021514216760256), np.float64(0.577349096556258), np.float64(0.543010536751465), np.float64(0.6017217784026478), np.float64(0.49980901248959725), np.float64(0.549025762104577), np.float64(0.6608768153096375), np.float64(0.4928578546099284), np.float64(0.5348841376150667), np.float64(0.556005739015535), np.float64(0.5640547588128902), np.float64(0.5559214413050606), np.float64(0.5698832770583323), np.float64(0.560458666314673), np.float64(0.6988524212040286), np.float64(0.6376337874921687), np.float64(0.5560196605647416), np.float64(0.6127714103560864), np.float64(0.6760668463440722), np.float64(0.5809846778877168), np.float64(0.5739511467848285), np.float64(0.6140513271428404), np.float64(0.4975781640051301), np.float64(0.5285224550380395), np.float64(0.5933226304693295), np.float64(0.5730203939182265), np.float64(0.5970974368744941), np.float64(0.6454481429188669), np.float64(0.5635728741967315), np.float64(0.528125560802951), np.float64(0.5040982679032727), np.float64(0.6653565012572435), np.float64(0.5985574735142795), np.float64(0.730228610958798), np.float64(0.6285716884814999), np.float64(0.5234678019165439), np.float64(0.5713397141878831), np.float64(0.5717312156620087), np.float64(0.7042985319172644), np.float64(0.63755612616981), np.float64(0.6951714632423653), np.float64(0.6730273787427163), np.float64(0.6376584135707052), np.float64(0.4833472226453938), np.float64(0.6066793461781481), np.float64(0.6082104969505544), np.float64(0.6459812108557361), np.float64(0.5432803127020904), np.float64(0.5337197141272741), np.float64(0.5338811447645376), np.float64(0.5092632772967755), np.float64(0.5518719359455113), np.float64(0.5403502054464175), np.float64(0.6056914643139776), np.float64(0.5906075585333678), np.float64(0.5726221473955107), np.float64(0.5788545814092241), np.float64(0.6657282734487572), np.float64(0.7218432015792289), np.float64(0.546536059247729), np.float64(0.42741019003594255), np.float64(0.5469945101174245), np.float64(0.5872749205061726), np.float64(0.5897552976232735), np.float64(0.5283874297509904), np.float64(0.6445616082933314), np.float64(0.637771626111185), np.float64(0.5114427944522293), np.float64(0.6647125769674491), np.float64(0.6866740560102996), np.float64(0.5525720852767623), np.float64(0.48944999169683845), np.float64(0.7365429440693598), np.float64(0.5594886009378093), np.float64(0.4961736434683059), np.float64(0.6470929930072038), np.float64(0.642957897363865), np.float64(0.6781195860168208), np.float64(0.6095753392557824), np.float64(0.5399740952840107), np.float64(0.5802845368779976), np.float64(0.6546906958737687), np.float64(0.6764424914687107), np.float64(0.5304222765954769), np.float64(0.6574796160501574), np.float64(0.5755440060005387), np.float64(0.5598081682249334), np.float64(0.6593878469500024), np.float64(0.5835234829297943), np.float64(0.5006603780052039), np.float64(0.6713060566617219), np.float64(0.6459224698530263), np.float64(0.5378135240316395), np.float64(0.5392995653934171), np.float64(0.6546609102438407), np.float64(0.5910433510852474)]

In [43]:
threshold = np.array(data_for_threshold).mean()
print(threshold)

0.5889084034855399

In [44]:
output = [1 if x > threshold else 0 for x in data_for_threshold]
print(output)

[1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1]

In [45]:
report_manual = classification_report(y_test, output)
print(report_manual)

              precision    recall  f1-score   support

           0       0.90      0.73      0.80        99
           1       0.64      0.85      0.73        55

    accuracy                           0.77       154
   macro avg       0.77      0.79      0.77       154
weighted avg       0.81      0.77      0.78       154